<a href="https://colab.research.google.com/github/j88k77/Hunar-Intern/blob/main/hunar_ml_task1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

while True:
  try:
    order = int(input('give order for the matrix '))
    break
  except ValueError:
    print("Invalid input. Please enter an integer.")

matrix = np.zeros((order, order), dtype=int)

print(f"enter {order*order} elements for the matrix")

for i in range(order):
    for j in range(order):
        while True:
          try:
            matrix[i, j] = int(input(f"enter element [{i},{j}] for the matrix "))
            break
          except ValueError:
            print("Invalid input. Please enter an integer.")

print("matrix :")
print(matrix)

sumdiagonal = 0
for i in range(order):
    sumdiagonal += matrix[i, i]

print("Sum of diagonal elements:", sumdiagonal)

give order for the matrix 3
enter 9 elements for the matrix
enter element [0,0] for the matrix 4
enter element [0,1] for the matrix 6
enter element [0,2] for the matrix 8
enter element [1,0] for the matrix 12
enter element [1,1] for the matrix 4
enter element [1,2] for the matrix 7
enter element [2,0] for the matrix 0
enter element [2,1] for the matrix 3
enter element [2,2] for the matrix 6
matrix :
[[ 4  6  8]
 [12  4  7]
 [ 0  3  6]]
Sum of diagonal elements: 14
